version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile_App
    container_name: "app"
    ports:
      - "8080:8080"
    restart: "unless-stopped"

  mongodb:
    image: mongo
    container_name: mongodb-commission
    command: mongod --port 27018
    ports:
        - "27018:27018"